export interface Person {
  id: string;
  firstName: string;
  lastName: string;
  birthDate?: string;
  deathDate?: string;
  birthPlace?: string;
  photo?: string;
  isYou?: boolean;
  spouseId?: string;
  parentId?: string;
  generation: number;
}

export interface FamilyTree {
  rootId: string;
  people: Record<string, Person>;
}

export const loremFamily: FamilyTree = {
  rootId: "dan",
  people: {
    dan: {
      id: "dan",
      firstName: "Dan",
      lastName: "Oak",
      birthDate: "1994-06-28",
      isYou: true,
      spouseId: "libby",
      parentId: "valerie",
      generation: 0,
    },
    libby: {
      id: "libby",
      firstName: "Elisabeth",
      lastName: "Oak",
      birthDate: "1994-12-09",
      spouseId: "dan",
      parentId: "gill",
      generation: 0,
    },
    arthur: {
      id: "arthur",
      firstName: "Arthur",
      lastName: "Oak",
      birthDate: "2024-10-29",
      parentId: "dan",
      generation: -1,
    },
    valerie: {
      id: "valerie",
      firstName: "Valerie",
      lastName: "McAllister",
      birthDate: "1969-03-15",
      spouseId: "paul",
      parentId: "bruce",
      generation: 1,
    },
    paul: {
      id: "paul",
      firstName: "Paul",
      lastName: "Scott",
      birthDate: "1966-05-11",
      spouseId: "valerie",
      generation: 1,
    },
    katie: {
      id: "katie",
      firstName: "Katie",
      lastName: "Hutchings",
      birthDate: "1993-05-11",
      spouseId: "george",
      parentId: "valerie",
      generation: 0,
    },
    charlotte: {
      id: "charlotte",
      firstName: "Charlotte",
      lastName: "McAllister",
      birthDate: "1991-05-20",
      spouseId: "matthew",
      parentId: "valerie",
      generation: 0,
    },
    mike: {
      id: "mike",
      firstName: "Mike",
      lastName: "McAllister",
      birthDate: "1999-10-20",
      spouseId: "phoenix",
      parentId: "valerie",
      generation: 0,
    },
    matthew: {
      id: "matthew",
      firstName: "Matthew",
      lastName: "Barnes",
      spouseId: "charlotte",
      generation: 0,
    },
    george: {
      id: "george",
      firstName: "George",
      lastName: "Hutchings",
      spouseId: "katie",
      generation: 0,
    },
    jasmine: {
      id: "jasmine",
      firstName: "Jasmine",
      lastName: "Beagley",
      birthDate: "2011-05-03",
      parentId: "katie",
      generation: -1,
    },
    lewis: {
      id: "lewis",
      firstName: "Lewis",
      lastName: "Beagley",
      birthDate: "2013-01-15",
      parentId: "katie",
      generation: -1,
    },
    riley: {
      id: "riley",
      firstName: "Riley",
      lastName: "Hutchings",
      birthDate: "2016-04-01",
      parentId: "katie",
      generation: -1,
    },
    maddie: {
      id: "maddie",
      firstName: "Maddie",
      lastName: "Hutchings",
      birthDate: "2021-12-30",
      parentId: "katie",
      generation: -1,
    },
    elsie: {
      id: "elsie",
      firstName: "Elsie",
      lastName: "Hutchings",
      birthDate: "2024-10-06",
      parentId: "katie",
      generation: -1,
    },
    phoenix: {
      id: "phoenix",
      firstName: "Phoenix",
      lastName: "",
      spouseId: "mike",
      generation: 0,
    },
    gill: {
      id: "gill",
      firstName: "Gill",
      lastName: "Brown",
      birthDate: "",
      spouseId: "david",
      parentId: "shirley",
      generation: 1,
    },
    david: {
      id: "david",
      firstName: "David",
      lastName: "Brown",
      spouseId: "gill",
      generation: 1,
    },
    andrewBrown: {
      id: "andrewBrown",
      firstName: "Andrew",
      lastName: "Brown",
      parentId: "gill",
      generation: 0,
    },
    shirley: {
      id: "shirley",
      firstName: "Shirley",
      lastName: "Dawes",
      spouseId: "dennis",
      generation: 2,
    },
    dennis: {
      id: "dennis",
      firstName: "Dennis",
      lastName: "Dawes",
      spouseId: "shirley",
      generation: 2,
    },
    mary: {
      id: "mary",
      firstName: "Mary",
      lastName: "Wright",
      birthDate: "",
      spouseId: "simon",
      parentId: "shirley",
      generation: 1,
    },
    simon: {
      id: "simon",
      firstName: "Simon",
      lastName: "Wright",
      spouseId: "mary",
      deathDate: "",
      generation: 1,
    },
    adam: {
      id: "adam",
      firstName: "Adam",
      lastName: "Wright",
      spouseId: "andrea",
      parentId: "mary",
      generation: 0,
    },
    andrea: {
      id: "andrea",
      firstName: "Andrea",
      lastName: "Wright",
      spouseId: "adam",
      generation: 0,
    },
    emma: {
      id: "emma",
      firstName: "Emma",
      lastName: "Wright",
      parentId: "mary",
      generation: 0,
    },
    danConner: {
      id: "danConner",
      firstName: "Dan",
      lastName: "Conner",
      spouseId: "emma",
      generation: 0,
    },
    bruce: {
      id: "bruce",
      firstName: "Bruce",
      lastName: "McAllister",
      spouseId: "sandra",
      generation: 2,
    },
    sandra: {
      id: "sandra",
      firstName: "Sandra",
      lastName: "McAllister",
      spouseId: "bruce",
      generation: 2,
    },
    christopher: {
      id: "christopher",
      firstName: "Christopher",
      lastName: "McAllister",
      spouseId: "steph",
      parentId: "bruce",
      generation: 1,
    },
    steph: {
      id: "steph",
      firstName: "Steph",
      lastName: "Roseblade",
      spouseId: "christopher",
      generation: 1,
    },
    matthewRoseblade: {
      id: "matthewRoseblade",
      firstName: "Matthew",
      lastName: "Roseblade",
      parentId: "christopher",
      generation: 0,
    },
    donald: {
      id: "donald",
      firstName: "Donald",
      lastName: "McAllister",
      spouseId: "lisa",
      parentId: "bruce",
      generation: 1,
    },
    rachel: {
      id: "rachel",
      firstName: "Rachel",
      lastName: "",
      spouseId: "donald",
      generation: 1,
    },
    andrewParacha: {
      id: "andrewParacha",
      firstName: "Andrew",
      lastName: "Paracha",
      spouseId: "mehreen",
      parentId: "donald",
      generation: 0,
    },
    mehreen: {
      id: "mehreen",
      firstName: "Mehreen",
      lastName: "Paracha",
      spouseId: "andrewParacha",
      generation: 0,
    },
    heather: {
      id: "heather",
      firstName: "Heather",
      lastName: "McAllister",
      parentId: "donald",
      generation: 0,
    },
    lisa: {
      id: "lisa",
      firstName: "Lisa",
      lastName: "McAllister",
      spouseId: "donald",
      generation: 1,
    },
    ryan: {
      id: "ryan",
      firstName: "Ryan",
      lastName: "McAllister",
      parentId: "donald",
      generation: 0,
    },
  },
};
